## Extracción de datos del IPC desde la API del INE

### Objetivo
Este notebook tiene como finalidad la extracción, exploración y estructuración de los datos del **Índice de Precios de Consumo (IPC)** publicados por el **Instituto Nacional de Estadística (INE)** a través de su API pública TEMPUS. 

A partir de la serie de datos IPCA (IPC Armonizado) con periodicidad mensual, se construye un **modelo dimensional** compuesto por:
- **Dimensiones**: tabla de tiempo (*tiempo*), tabla de territorios (*territorio*), tabla de sectores IPC (*sectores_ipc*) y tabla de tipos de medida (*tipo_medida*).
- **Tabla de hechos**: tabla central (*ipc*) que relaciona cada observación del índice con sus dimensiones asociadas.

### Metodología
1. **Conexión a la API del INE** — Llamada al endpoint `/DATOS_TABLA/76136` para obtener los últimos 60 periodos mensuales.
2. **Extracción de dimensiones** — Recorrido de la respuesta JSON para poblar las tablas dimensionales, garantizando unicidad mediante filtros de clave.
3. **Construcción de la tabla de hechos** — Cruce de las dimensiones a través de identificadores primarios y asignación del valor del IPC a cada combinación (territorio, sector, medida, periodo).
4. **Exportación** — Volcado de cada tabla a ficheros CSV en `../files/data_raw/` para su consumo en etapas posteriores del pipeline.

### Contexto del proyecto
Estos datos se integran en un análisis más amplio sobre la **resiliencia empresarial en España**, donde se combinarán con información de constitución y disolución de empresas para estudiar la correlación entre el entorno macroeconómico (inflación) y la actividad empresarial.

In [1]:
# Configuración del sistema para encontrar la carpeta raíz
import sys
import os

import pandas as pd
# Esto obliga a Python a mirar una carpeta hacia atrás (donde está 'src')
sys.path.append(os.path.abspath(os.path.join('..')))
sys.path.append(os.path.abspath(os.path.join('.')))

# Importación del módulo de conexión a la API
from src.api import connection_api as conexion_api
from src.api.config import API_URLS

In [2]:
url = API_URLS["ipc"]

In [3]:
data = conexion_api.llamada_api(url)

In [4]:
len(data)

1120

In [5]:
data[70]['Nombre']    #Ruta al nombre

'Andalucía. Vestido y calzado. Variación anual. '

In [6]:
data[0]['Data'][0]['Periodo']['Mes_inicio']     #Ruta al mes

'5'

In [7]:
data[0]['Data'][0]['Anyo']       #Ruta al año

2026

In [8]:
data[0]['Data'][0]['Periodo']['Nombre_largo']       #Ruta al nombre del mes

'Mayo'

In [9]:
data[0]['Data'][0]['Valor']             #Ruta al IPC

102.951

In [10]:
data[0]['Data']

[{'Fecha': 1777586400000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 5,
   'Valor': 5,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '5',
   'Codigo': '05',
   'Nombre': 'M05',
   'Nombre_largo': 'Mayo'},
  'Anyo': 2026,
  'NombrePeriodo': '2026M05',
  'CodigoPeriodo': '202605',
  'Valor': 102.951,
  'Secreto': False},
 {'Fecha': 1774994400000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 4,
   'Valor': 4,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '4',
   'Codigo': '04',
   'Nombre': 'M04',
   'Nombre_largo': 'Abril'},
  'Anyo': 2026,
  'NombrePeriodo': '2026M04',
  'CodigoPeriodo': '202604',
  'Valor': 102.883,
  'Secreto': False},
 {'Fecha': 1772319600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 3,
   'Valor': 3,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '3',
   'Codigo': '03',
   'Nombre': 'M03',
   'Nombre_largo': 'Marzo'},
  'Anyo': 2026,
  'NombrePeriodo': '2026M03',
  'CodigoPeriodo': '202603',
  'Valor': 102.44,
  'Secreto': False},
 {'Fecha': 1769900400000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 2,
   'Valor': 2,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '2',
   'Codigo': '02',
   'Nombre': 'M02',
   'Nombre_largo': 'Febrero'},
  'Anyo': 2026,
  'NombrePeriodo': '2026M02',
  'CodigoPeriodo': '202602',
  'Valor': 101.261,
  'Secreto': False},
 {'Fecha': 1767222000000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 1,
   'Valor': 1,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '1',
   'Codigo': '01',
   'Nombre': 'M01',
   'Nombre_largo': 'Enero'},
  'Anyo': 2026,
  'NombrePeriodo': '2026M01',
  'CodigoPeriodo': '202601',
  'Valor': 100.836,
  'Secreto': False},
 {'Fecha': 1764543600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 12,
   'Valor': 12,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '12',
   'Codigo': '12',
   'Nombre': 'M12',
   'Nombre_largo': 'Diciembre'},
  'Anyo': 2025,
  'NombrePeriodo': '2025M12',
  'CodigoPeriodo': '202512',
  'Valor': 101.289,
  'Secreto': False},
 {'Fecha': 1761951600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 11,
   'Valor': 11,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '11',
   'Codigo': '11',
   'Nombre': 'M11',
   'Nombre_largo': 'Noviembre'},
  'Anyo': 2025,
  'NombrePeriodo': '2025M11',
  'CodigoPeriodo': '202511',
  'Valor': 100.943,
  'Secreto': False},
 {'Fecha': 1759269600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 10,
   'Valor': 10,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '10',
   'Codigo': '10',
   'Nombre': 'M10',
   'Nombre_largo': 'Octubre'},
  'Anyo': 2025,
  'NombrePeriodo': '2025M10',
  'CodigoPeriodo': '202510',
  'Valor': 100.748,
  'Secreto': False},
 {'Fecha': 1756677600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 9,
   'Valor': 9,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '9',
   'Codigo': '09',
   'Nombre': 'M09',
   'Nombre_largo': 'Septiembre'},
  'Anyo': 2025,
  'NombrePeriodo': '2025M09',
  'CodigoPeriodo': '202509',
  'Valor': 100.059,
  'Secreto': False},
 {'Fecha': 1753999200000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 8,
   'Valor': 8,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '8',
   'Codigo': '08',
   'Nombre': 'M08',
   'Nombre_largo': 'Agosto'},
  'Anyo': 2025,
  'NombrePeriodo': '2025M08',
  'CodigoPeriodo': '202508',
  'Valor': 100.345,
  'Secreto': False},
 {'Fecha': 1751320800000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 7,
   'Valor': 7,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '7',
   'Codigo': '07',
   'Nombre': 'M07',
   'Nombre_largo': 'Julio'},
  'Anyo': 2025,
  'NombrePeriodo': '2025M07',
  'CodigoPeriodo': '202507',
  'Valor': 100.305,
  'Secreto': False},
 {'Fecha': 1748728800000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 6,
   'Valor': 6,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '6',
   'Codigo': '06',
   'Nombre': 'M06',
   'Nombre_largo': 'Junio'},
  'Anyo': 2025,
  'NombrePeriodo': '2025M06',
  'CodigoPeriodo': '202506',
  'Valor': 100.382,
  'Secreto': False},
 {'Fecha': 1746050400000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 5,
   'Valor': 5,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '5',
   'Codigo': '05',
   'Nombre': 'M05',
   'Nombre_largo': 'Mayo'},
  'Anyo': 2025,
  'NombrePeriodo': '2025M05',
  'CodigoPeriodo': '202505',
  'Valor': 99.714,
  'Secreto': False},
 {'Fecha': 1743458400000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 4,
   'Valor': 4,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '4',
   'Codigo': '04',
   'Nombre': 'M04',
   'Nombre_largo': 'Abril'},
  'Anyo': 2025,
  'NombrePeriodo': '2025M04',
  'CodigoPeriodo': '202504',
  'Valor': 99.647,
  'Secreto': False},
 {'Fecha': 1740783600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 3,
   'Valor': 3,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '3',
   'Codigo': '03',
   'Nombre': 'M03',
   'Nombre_largo': 'Marzo'},
  'Anyo': 2025,
  'NombrePeriodo': '2025M03',
  'CodigoPeriodo': '202503',
  'Valor': 99.024,
  'Secreto': False},
 {'Fecha': 1738364400000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 2,
   'Valor': 2,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '2',
   'Codigo': '02',
   'Nombre': 'M02',
   'Nombre_largo': 'Febrero'},
  'Anyo': 2025,
  'NombrePeriodo': '2025M02',
  'CodigoPeriodo': '202502',
  'Valor': 98.966,
  'Secreto': False},
 {'Fecha': 1735686000000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 1,
   'Valor': 1,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '1',
   'Codigo': '01',
   'Nombre': 'M01',
   'Nombre_largo': 'Enero'},
  'Anyo': 2025,
  'NombrePeriodo': '2025M01',
  'CodigoPeriodo': '202501',
  'Valor': 98.579,
  'Secreto': False},
 {'Fecha': 1733007600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 12,
   'Valor': 12,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '12',
   'Codigo': '12',
   'Nombre': 'M12',
   'Nombre_largo': 'Diciembre'},
  'Anyo': 2024,
  'NombrePeriodo': '2024M12',
  'CodigoPeriodo': '202412',
  'Valor': 98.411,
  'Secreto': False},
 {'Fecha': 1730415600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 11,
   'Valor': 11,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '11',
   'Codigo': '11',
   'Nombre': 'M11',
   'Nombre_largo': 'Noviembre'},
  'Anyo': 2024,
  'NombrePeriodo': '2024M11',
  'CodigoPeriodo': '202411',
  'Valor': 97.968,
  'Secreto': False},
 {'Fecha': 1727733600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 10,
   'Valor': 10,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '10',
   'Codigo': '10',
   'Nombre': 'M10',
   'Nombre_largo': 'Octubre'},
  'Anyo': 2024,
  'NombrePeriodo': '2024M10',
  'CodigoPeriodo': '202410',
  'Valor': 97.729,
  'Secreto': False},
 {'Fecha': 1725141600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 9,
   'Valor': 9,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '9',
   'Codigo': '09',
   'Nombre': 'M09',
   'Nombre_largo': 'Septiembre'},
  'Anyo': 2024,
  'NombrePeriodo': '2024M09',
  'CodigoPeriodo': '202409',
  'Valor': 97.123,
  'Secreto': False},
 {'Fecha': 1722463200000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 8,
   'Valor': 8,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '8',
   'Codigo': '08',
   'Nombre': 'M08',
   'Nombre_largo': 'Agosto'},
  'Anyo': 2024,
  'NombrePeriodo': '2024M08',
  'CodigoPeriodo': '202408',
  'Valor': 97.713,
  'Secreto': False},
 {'Fecha': 1719784800000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 7,
   'Valor': 7,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '7',
   'Codigo': '07',
   'Nombre': 'M07',
   'Nombre_largo': 'Julio'},
  'Anyo': 2024,
  'NombrePeriodo': '2024M07',
  'CodigoPeriodo': '202407',
  'Valor': 97.673,
  'Secreto': False},
 {'Fecha': 1717192800000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 6,
   'Valor': 6,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '6',
   'Codigo': '06',
   'Nombre': 'M06',
   'Nombre_largo': 'Junio'},
  'Anyo': 2024,
  'NombrePeriodo': '2024M06',
  'CodigoPeriodo': '202406',
  'Valor': 98.139,
  'Secreto': False},
 {'Fecha': 1714514400000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 5,
   'Valor': 5,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '5',
   'Codigo': '05',
   'Nombre': 'M05',
   'Nombre_largo': 'Mayo'},
  'Anyo': 2024,
  'NombrePeriodo': '2024M05',
  'CodigoPeriodo': '202405',
  'Valor': 97.771,
  'Secreto': False},
 {'Fecha': 1711922400000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 4,
   'Valor': 4,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '4',
   'Codigo': '04',
   'Nombre': 'M04',
   'Nombre_largo': 'Abril'},
  'Anyo': 2024,
  'NombrePeriodo': '2024M04',
  'CodigoPeriodo': '202404',
  'Valor': 97.514,
  'Secreto': False},
 {'Fecha': 1709247600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 3,
   'Valor': 3,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '3',
   'Codigo': '03',
   'Nombre': 'M03',
   'Nombre_largo': 'Marzo'},
  'Anyo': 2024,
  'NombrePeriodo': '2024M03',
  'CodigoPeriodo': '202403',
  'Valor': 96.84,
  'Secreto': False},
 {'Fecha': 1706742000000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 2,
   'Valor': 2,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '2',
   'Codigo': '02',
   'Nombre': 'M02',
   'Nombre_largo': 'Febrero'},
  'Anyo': 2024,
  'NombrePeriodo': '2024M02',
  'CodigoPeriodo': '202402',
  'Valor': 96.108,
  'Secreto': False},
 {'Fecha': 1704063600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 1,
   'Valor': 1,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '1',
   'Codigo': '01',
   'Nombre': 'M01',
   'Nombre_largo': 'Enero'},
  'Anyo': 2024,
  'NombrePeriodo': '2024M01',
  'CodigoPeriodo': '202401',
  'Valor': 95.768,
  'Secreto': False},
 {'Fecha': 1701385200000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 12,
   'Valor': 12,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '12',
   'Codigo': '12',
   'Nombre': 'M12',
   'Nombre_largo': 'Diciembre'},
  'Anyo': 2023,
  'NombrePeriodo': '2023M12',
  'CodigoPeriodo': '202312',
  'Valor': 95.687,
  'Secreto': False},
 {'Fecha': 1698793200000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 11,
   'Valor': 11,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '11',
   'Codigo': '11',
   'Nombre': 'M11',
   'Nombre_largo': 'Noviembre'},
  'Anyo': 2023,
  'NombrePeriodo': '2023M11',
  'CodigoPeriodo': '202311',
  'Valor': 95.663,
  'Secreto': False},
 {'Fecha': 1696111200000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 10,
   'Valor': 10,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '10',
   'Codigo': '10',
   'Nombre': 'M10',
   'Nombre_largo': 'Octubre'},
  'Anyo': 2023,
  'NombrePeriodo': '2023M10',
  'CodigoPeriodo': '202310',
  'Valor': 95.998,
  'Secreto': False},
 {'Fecha': 1693519200000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 9,
   'Valor': 9,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '9',
   'Codigo': '09',
   'Nombre': 'M09',
   'Nombre_largo': 'Septiembre'},
  'Anyo': 2023,
  'NombrePeriodo': '2023M09',
  'CodigoPeriodo': '202309',
  'Valor': 95.721,
  'Secreto': False},
 {'Fecha': 1690840800000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 8,
   'Valor': 8,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '8',
   'Codigo': '08',
   'Nombre': 'M08',
   'Nombre_largo': 'Agosto'},
  'Anyo': 2023,
  'NombrePeriodo': '2023M08',
  'CodigoPeriodo': '202308',
  'Valor': 95.552,
  'Secreto': False},
 {'Fecha': 1688162400000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 7,
   'Valor': 7,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '7',
   'Codigo': '07',
   'Nombre': 'M07',
   'Nombre_largo': 'Julio'},
  'Anyo': 2023,
  'NombrePeriodo': '2023M07',
  'CodigoPeriodo': '202307',
  'Valor': 95.042,
  'Secreto': False},
 {'Fecha': 1685570400000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 6,
   'Valor': 6,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '6',
   'Codigo': '06',
   'Nombre': 'M06',
   'Nombre_largo': 'Junio'},
  'Anyo': 2023,
  'NombrePeriodo': '2023M06',
  'CodigoPeriodo': '202306',
  'Valor': 94.881,
  'Secreto': False},
 {'Fecha': 1682892000000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 5,
   'Valor': 5,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '5',
   'Codigo': '05',
   'Nombre': 'M05',
   'Nombre_largo': 'Mayo'},
  'Anyo': 2023,
  'NombrePeriodo': '2023M05',
  'CodigoPeriodo': '202305',
  'Valor': 94.345,
  'Secreto': False},
 {'Fecha': 1680300000000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 4,
   'Valor': 4,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '4',
   'Codigo': '04',
   'Nombre': 'M04',
   'Nombre_largo': 'Abril'},
  'Anyo': 2023,
  'NombrePeriodo': '2023M04',
  'CodigoPeriodo': '202304',
  'Valor': 94.39,
  'Secreto': False},
 {'Fecha': 1677625200000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 3,
   'Valor': 3,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '3',
   'Codigo': '03',
   'Nombre': 'M03',
   'Nombre_largo': 'Marzo'},
  'Anyo': 2023,
  'NombrePeriodo': '2023M03',
  'CodigoPeriodo': '202303',
  'Valor': 93.831,
  'Secreto': False},
 {'Fecha': 1675206000000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 2,
   'Valor': 2,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '2',
   'Codigo': '02',
   'Nombre': 'M02',
   'Nombre_largo': 'Febrero'},
  'Anyo': 2023,
  'NombrePeriodo': '2023M02',
  'CodigoPeriodo': '202302',
  'Valor': 93.487,
  'Secreto': False},
 {'Fecha': 1672527600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 1,
   'Valor': 1,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '1',
   'Codigo': '01',
   'Nombre': 'M01',
   'Nombre_largo': 'Enero'},
  'Anyo': 2023,
  'NombrePeriodo': '2023M01',
  'CodigoPeriodo': '202301',
  'Valor': 92.613,
  'Secreto': False},
 {'Fecha': 1669849200000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 12,
   'Valor': 12,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '12',
   'Codigo': '12',
   'Nombre': 'M12',
   'Nombre_largo': 'Diciembre'},
  'Anyo': 2022,
  'NombrePeriodo': '2022M12',
  'CodigoPeriodo': '202212',
  'Valor': 92.808,
  'Secreto': False},
 {'Fecha': 1667257200000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 11,
   'Valor': 11,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '11',
   'Codigo': '11',
   'Nombre': 'M11',
   'Nombre_largo': 'Noviembre'},
  'Anyo': 2022,
  'NombrePeriodo': '2022M11',
  'CodigoPeriodo': '202211',
  'Valor': 92.669,
  'Secreto': False},
 {'Fecha': 1664575200000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 10,
   'Valor': 10,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '10',
   'Codigo': '10',
   'Nombre': 'M10',
   'Nombre_largo': 'Octubre'},
  'Anyo': 2022,
  'NombrePeriodo': '2022M10',
  'CodigoPeriodo': '202210',
  'Valor': 92.78,
  'Secreto': False},
 {'Fecha': 1661983200000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 9,
   'Valor': 9,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '9',
   'Codigo': '09',
   'Nombre': 'M09',
   'Nombre_largo': 'Septiembre'},
  'Anyo': 2022,
  'NombrePeriodo': '2022M09',
  'CodigoPeriodo': '202209',
  'Valor': 92.47,
  'Secreto': False},
 {'Fecha': 1659304800000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 8,
   'Valor': 8,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '8',
   'Codigo': '08',
   'Nombre': 'M08',
   'Nombre_largo': 'Agosto'},
  'Anyo': 2022,
  'NombrePeriodo': '2022M08',
  'CodigoPeriodo': '202208',
  'Valor': 93.117,
  'Secreto': False},
 {'Fecha': 1656626400000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 7,
   'Valor': 7,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '7',
   'Codigo': '07',
   'Nombre': 'M07',
   'Nombre_largo': 'Julio'},
  'Anyo': 2022,
  'NombrePeriodo': '2022M07',
  'CodigoPeriodo': '202207',
  'Valor': 92.881,
  'Secreto': False},
 {'Fecha': 1654034400000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 6,
   'Valor': 6,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '6',
   'Codigo': '06',
   'Nombre': 'M06',
   'Nombre_largo': 'Junio'},
  'Anyo': 2022,
  'NombrePeriodo': '2022M06',
  'CodigoPeriodo': '202206',
  'Valor': 93.118,
  'Secreto': False},
 {'Fecha': 1651356000000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 5,
   'Valor': 5,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '5',
   'Codigo': '05',
   'Nombre': 'M05',
   'Nombre_largo': 'Mayo'},
  'Anyo': 2022,
  'NombrePeriodo': '2022M05',
  'CodigoPeriodo': '202205',
  'Valor': 91.426,
  'Secreto': False},
 {'Fecha': 1648764000000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 4,
   'Valor': 4,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '4',
   'Codigo': '04',
   'Nombre': 'M04',
   'Nombre_largo': 'Abril'},
  'Anyo': 2022,
  'NombrePeriodo': '2022M04',
  'CodigoPeriodo': '202204',
  'Valor': 90.676,
  'Secreto': False},
 {'Fecha': 1646089200000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 3,
   'Valor': 3,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '3',
   'Codigo': '03',
   'Nombre': 'M03',
   'Nombre_largo': 'Marzo'},
  'Anyo': 2022,
  'NombrePeriodo': '2022M03',
  'CodigoPeriodo': '202203',
  'Valor': 90.837,
  'Secreto': False},
 {'Fecha': 1643670000000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 2,
   'Valor': 2,
   'FK_Periodicidad': 1,
   'Dia_inicio': '1',
   'Mes_inicio': '2',
   'Codigo': '02',
   'Nombre': 'M02',
   'Nombre_largo': 'Febrero'},
  'Anyo': 2022,
  'NombrePeriodo': '2022M02',
  'CodigoPeriodo': '202202',
  'Valor': 88.167,
  'Secreto': False},
 {'Fecha': 1640991600000,
  'TipoDato': {'Id': 1, 'Nombre': 'Definitivo', 'Codigo': 'D'},
  'Periodo': {'Id': 1,
   'Valor': 1,

In [13]:
tiempo = {'id_tiempo': [], 'anio': [], 'mes': [], 'nombre_mes': [] }

for serie in data:
    for dato in serie['Data']:
        if dato['CodigoPeriodo'] not in tiempo['id_tiempo']:
            tiempo['id_tiempo'].append(dato['CodigoPeriodo'])
            tiempo['anio'].append(dato['Anyo'])
            tiempo['mes'].append(dato['Periodo']['Mes_inicio'])
            tiempo['nombre_mes'].append(dato['Periodo']['Nombre_largo'])

In [14]:
tiempo = pd.DataFrame(tiempo)
tiempo.sample()

    id_tiempo  anio mes nombre_mes
256    200501  2005   1      Enero

In [15]:
tiempo.shape

(294, 4)

In [16]:
tiempo.to_csv('../files/data_raw/tiempo.csv', index=False)

In [17]:
territorio = {'id_territorio': [], 'nombre_territorio': []}
id_ter = 1

for serie in data:
    nombre_completo = serie['Nombre']
    nombre_limpio = nombre_completo.split('.')[0].strip()

    if nombre_limpio not in territorio['nombre_territorio']:
        territorio['id_territorio'].append(id_ter)
        territorio['nombre_territorio'].append(nombre_limpio)

        id_ter += 1

In [18]:
territorio = pd.DataFrame(territorio)
territorio.sample()

   id_territorio        nombre_territorio
3              4  Asturias, Principado de

In [19]:
territorio.shape

(20, 2)

In [20]:
territorio.to_csv('../files/data_raw/territorio.csv', index=False)

In [21]:
sectores_ipc = {'id_sector': [], 'nombre_sector': []}
id_sec = 1

for serie in data:
    nombre_completo = serie['Nombre']
    sector_limpio = nombre_completo.split('.')[1].strip()

    if sector_limpio not in sectores_ipc['nombre_sector']:
        sectores_ipc['id_sector'].append(id_sec)
        sectores_ipc['nombre_sector'].append(sector_limpio)

        id_sec += 1

In [22]:
sectores_ipc = pd.DataFrame(sectores_ipc)

In [23]:
sectores_ipc

    id_sector                                      nombre_sector
0           1                                     Índice general
1           2                 Alimentos y bebidas no alcohólicas
2           3                       Bebidas alcohólicas y tabaco
3           4                                  Vestido y calzado
4           5  Vivienda, agua, electricidad, gas y otros comb...
5           6  Muebles, artículos del hogar y artículos para ...
6           7                                            Sanidad
7           8                                         Transporte
8           9                       Información y comunicaciones
9          10         Actividades recreativas, deporte y cultura
10         11                                          Enseñanza
11         12            Restaurantes y servicios de alojamiento
12         13                    Seguros y servicios financieros
13         14  Cuidado personal, protección social, y bienes ...

In [24]:
sectores_ipc.to_csv('../files/data_raw/sectores_ipc.csv', index=False)

In [25]:
tipo_medida = {'id_medida': [], 'nombre_medida': []}
id_med = 1

for serie in data:
    nombre_completo = serie['Nombre']
    medida_limpio = nombre_completo.split('.')[2].strip()

    if medida_limpio not in tipo_medida['nombre_medida']:
        tipo_medida['id_medida'].append(id_med)
        tipo_medida['nombre_medida'].append(medida_limpio)

        id_med += 1

In [26]:
tipo_medida

{'id_medida': [1, 2, 3, 4],
 'nombre_medida': ['Índice',
  'Variación mensual',
  'Variación anual',
  'Variación en lo que va de año']}

In [27]:
tipo_medida = pd.DataFrame(tipo_medida)

In [28]:
tipo_medida

   id_medida                  nombre_medida
0          1                         Índice
1          2              Variación mensual
2          3                Variación anual
3          4  Variación en lo que va de año

In [29]:
tipo_medida.to_csv('../files/data_raw/tipo_medida.csv', index=False)

In [ ]:
#  Creamos diccionarios

map_territorios = dict(zip(territorio['nombre_territorio'], territorio['id_territorio']))
map_sectores = dict(zip(sectores_ipc['nombre_sector'], sectores_ipc['id_sector']))
map_medidas = dict(zip(tipo_medida['nombre_medida'], tipo_medida['id_medida']))
 
ipc = {
    'id_tiempo': [],
    'id_territorio': [],
    'id_sector': [],
    'id_medida': [],
    'valor_ipc': []
}
 
# Extracción y Cruce de IDs
for serie in data:
    nombre_completo = serie['Nombre']
    partes = nombre_completo.split('.')
    if len(partes) >= 3:

        # Extraemos los nombres de texto limpio
        territorio_texto = partes[0].strip()
        sector_texto = partes[1].strip()
        medida_texto = partes[2].strip()

        # Miramos en nuestros mapas qué ID le toca a cada texto
        id_terr = map_territorios.get(territorio_texto)
        id_sec = map_sectores.get(sector_texto)
        id_med = map_medidas.get(medida_texto)

        # Si por algún motivo el INE da un texto que no guardamos antes, nos lo saltamos
        if id_terr is None or id_sec is None or id_med is None:
            continue

        # Bajamos al segundo nivel: los datos históricos de esta serie
        for dato in serie['Data']:
            valor = dato.get('Valor')
            id_time = dato.get('CodigoPeriodo')     # Sacamos el código del periodo para usarlo como ID de tiempo

            # Si tenemos todos los datos, appendeamos en la tabla
            if valor is not None and id_time is not None:
                ipc['id_tiempo'].append(str(id_time))
                ipc['id_territorio'].append(id_terr)
                ipc['id_sector'].append(id_sec)
                ipc['id_medida'].append(id_med)
                ipc['valor_ipc'].append(valor)

In [31]:
print(map_territorios)

{'Nacional': 1, 'Andalucía': 2, 'Aragón': 3, 'Asturias, Principado de': 4, 'Balears, Illes': 5, 'Canarias': 6, 'Cantabria': 7, 'Castilla y León': 8, 'Castilla - La Mancha': 9, 'Cataluña': 10, 'Comunitat Valenciana': 11, 'Extremadura': 12, 'Galicia': 13, 'Madrid, Comunidad de': 14, 'Murcia, Región de': 15, 'Navarra, Comunidad Foral de': 16, 'País Vasco': 17, 'Rioja, La': 18, 'Ceuta': 19, 'Melilla': 20}

In [32]:
print(ipc) # Print de control

{'id_tiempo': ['202605', '202604', '202603', '202602', '202601', '202512', '202511', '202510', '202509', '202508', '202507', '202506', '202505', '202504', '202503', '202502', '202501', '202412', '202411', '202410', '202409', '202408', '202407', '202406', '202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306', '202305', '202304', '202303', '202302', '202301', '202212', '202211', '202210', '202209', '202208', '202207', '202206', '202205', '202204', '202203', '202202', '202201', '202112', '202111', '202110', '202109', '202108', '202107', '202106', '202105', '202104', '202103', '202102', '202101', '202012', '202011', '202010', '202009', '202008', '202007', '202006', '202005', '202004', '202003', '202002', '202001', '201912', '201911', '201910', '201909', '201908', '201907', '201906', '201905', '201904', '201903', '201902', '201901', '201812', '201811', '201810', '201809', '201808', '201807', '201806', '201805', '201804', '201803', '201802', '201801', '201712', '201711', '201710', '201709', '201708', '201707', '201706', '201705', '201704', '201703', '201702', '201701', '201612', '201611', '201610', '201609', '201608', '201607', '201606', '201605', '201604', '201603', '201602', '201601', '201512', '201511', '201510', '201509', '201508', '201507', '201506', '201505', '201504', '201503', '201502', '201501', '201412', '201411', '201410', '201409', '201408', '201407', '201406', '201405', '201404', '201403', '201402', '201401', '201312', '201311', '201310', '201309', '201308', '201307', '201306', '201305', '201304', '201303', '201302', '201301', '201212', '201211', '201210', '201209', '201208', '201207', '201206', '201205', '201204', '201203', '201202', '201201', '201112', '201111', '201110', '201109', '201108', '201107', '201106', '201105', '201104', '201103', '201102', '201101', '201012', '201011', '201010', '201009', '201008', '201007', '201006', '201005', '201004', '201003', '201002', '201001', '200912', '200911', '200910', '200909', '200908', '200907', '200906', '200905', '200904', '200903', '200902', '200901', '200812', '200811', '200810', '200809', '200808', '200807', '200806', '200805', '200804', '200803', '200802', '200801', '200712', '200711', '200710', '200709', '200708', '200707', '200706', '200705', '200704', '200703', '200702', '200701', '200612', '200611', '200610', '200609', '200608', '200607', '200606', '200605', '200604', '200603', '200602', '200601', '200512', '200511', '200510', '200509', '200508', '200507', '200506', '200505', '200504', '200503', '200502', '200501', '200412', '200411', '200410', '200409', '200408', '200407', '200406', '200405', '200404', '200403', '200402', '200401', '200312', '200311', '200310', '200309', '200308', '200307', '200306', '200305', '200304', '200303', '200302', '200301', '200212', '200211', '200210', '200209', '200208', '200207', '200206', '200205', '200204', '200203', '200202', '200201', '202606', '202605', '202604', '202603', '202602', '202601', '202512', '202511', '202510', '202509', '202508', '202507', '202506', '202505', '202504', '202503', '202502', '202501', '202412', '202411', '202410', '202409', '202408', '202407', '202406', '202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306', '202305', '202304', '202303', '202302', '202301', '202212', '202211', '202210', '202209', '202208', '202207', '202206', '202205', '202204', '202203', '202202', '202201', '202112', '202111', '202110', '202109', '202108', '202107', '202106', '202105', '202104', '202103', '202102', '202101', '202012', '202011', '202010', '202009', '202008', '202007', '202006', '202005', '202004', '202003', '202002', '202001', '201912', '201911', '201910', '201909', '201908', '201907', '201906', '201905', '201904', '201903', '201902', '201901', '201812', '201811', '201810', '201809', '201808', '201807', '201806', '201805', '201804', '201803', '201802', '201801', '201712', '201711', '201710', '201709', '201708', '201707', '201706', '201705', '201704', '201703', '201702', '201701', '201612', '201611', '201610', '201609', '201608', '201607', '201606', '201605', '201604', '201603', '201602', '201601', '201512', '201511', '201510', '201509', '201508', '201507', '201506', '201505', '201504', '201503', '201502', '201501', '201412', '201411', '201410', '201409', '201408', '201407', '201406', '201405', '201404', '201403', '201402', '201401', '201312', '201311', '201310', '201309', '201308', '201307', '201306', '201305', '201304', '201303', '201302', '201301', '201212', '201211', '201210', '201209', '201208', '201207', '201206', '201205', '201204', '201203', '201202', '201201', '201112', '201111', '201110', '201109', '201108', '201107', '201106', '201105', '201104', '201103', '201102', '201101', '201012', '201011', '201010', '201009', '201008', '201007', '201006', '201005', '201004', '201003', '201002', '201001', '200912', '200911', '200910', '200909', '200908', '200907', '200906', '200905', '200904', '200903', '200902', '200901', '200812', '200811', '200810', '200809', '200808', '200807', '200806', '200805', '200804', '200803', '200802', '200801', '200712', '200711', '200710', '200709', '200708', '200707', '200706', '200705', '200704', '200703', '200702', '200701', '200612', '200611', '200610', '200609', '200608', '200607', '200606', '200605', '200604', '200603', '200602', '200601', '200512', '200511', '200510', '200509', '200508', '200507', '200506', '200505', '200504', '200503', '200502', '200501', '200412', '200411', '200410', '200409', '200408', '200407', '200406', '200405', '200404', '200403', '200402', '200401', '200312', '200311', '200310', '200309', '200308', '200307', '200306', '200305', '200304', '200303', '200302', '200301', '200212', '200211', '200210', '200209', '200208', '200207', '200206', '200205', '200204', '200203', '200202', '200201', '202606', '202605', '202604', '202603', '202602', '202601', '202512', '202511', '202510', '202509', '202508', '202507', '202506', '202505', '202504', '202503', '202502', '202501', '202412', '202411', '202410', '202409', '202408', '202407', '202406', '202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306', '202305', '202304', '202303', '202302', '202301', '202212', '202211', '202210', '202209', '202208', '202207', '202206', '202205', '202204', '202203', '202202', '202201', '202112', '202111', '202110', '202109', '202108', '202107', '202106', '202105', '202104', '202103', '202102', '202101', '202012', '202011', '202010', '202009', '202008', '202007', '202006', '202005', '202004', '202003', '202002', '202001', '201912', '201911', '201910', '201909', '201908', '201907', '201906', '201905', '201904', '201903', '201902', '201901', '201812', '201811', '201810', '201809', '201808', '201807', '201806', '201805', '201804', '201803', '201802', '201801', '201712', '201711', '201710', '201709', '201708', '201707', '201706', '201705', '201704', '201703', '201702', '201701', '201612', '201611', '201610', '201609', '201608', '201607', '201606', '201605', '201604', '201603', '201602', '201601', '201512', '201511', '201510', '201509', '201508', '201507', '201506', '201505', '201504', '201503', '201502', '201501', '201412', '201411', '201410', '201409', '201408', '201407', '201406', '201405', '201404', '201403', '201402', '201401', '201312', '201311', '201310', '201309', '201308', '201307', '201306', '201305', '201304', '201303', '201302', '201301', '201212', '201211', '201210', '201209', '201208', '201207', '201206', '201205', '201204', '201203', '201202', '201201', '201112', '201111', '201110', '201109', '201108', '201107', '201106', '201105', '201104', '201103', '201102', '201101', '201012', '201011', '201010', '201009', '201008', '201007', '201006', '201005', '201004', '201003', '201002', '201001', '200912', '200911', '200910', '200909', '200908', '200907', '200906', '200905', '200904', '200903', '200902', '200901', '200812', '200811', '200810', '200809', '200808', '200807', '200806', '200805', '200804', '200803', '200802', '200801', '200712', '200711', '200710', '200709', '200708', '200707', '200706', '200705', '200704', '200703', '200702', '200701', '200612', '200611', '200610', '200609', '200608', '200607', '200606', '200605', '200604', '200603', '200602', '200601', '200512', '200511', '200510', '200509', '200508', '200507', '200506', '200505', '200504', '200503', '200502', '200501', '200412', '200411', '200410', '200409', '200408', '200407', '200406', '200405', '200404', '200403', '200402', '200401', '200312', '200311', '200310', '200309', '200308', '200307', '200306', '200305', '200304', '200303', '200302', '200301', '200212', '200211', '200210', '200209', '200208', '200207', '200206', '200205', '200204', '200203', '200202', '200201', '202605', '202604', '202603', '202602', '202601', '202512', '202511', '202510', '202509', '202508', '202507', '202506', '202505', '202504', '202503', '202502', '202501', '202412', '202411', '202410', '202409', '202408', '202407', '202406', '202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306', '202305', '202304', '202303', '202302', '202301', '202212', '202211', '202210', '202209', '202208', '202207', '202206', '202205', '202204', '202203', '202202', '202201', '202112', '202111', '202110', '202109', '202108', '202107', '202106', '202105', '202104', '202103', '202102', '202101', '202012', '202011', '202010', '202009', '202008', '202007', '202006', '202005', '202004', '202003', '202002', '202001', '201912', '201911', '201910', '201909', '201908', '201907', '201906', '201905', '201904', '201903', '201902', '201901', '201812', '201811', '201810', '201809', '201808', '201807', '201806', '201805', '201804', '201803', '201802', '201801', '201712', '201711', '201710', '201709', '201708', '201707', '201706', '201705', '201704', '201703', '201702', '201701', '201612', '201611', '201610', '201609', '201608', '201607', '201606', '201605', '201604', '201603', '201602', '201601', '201512', '201511', '201510', '201509', '201508', '201507', '201506', '201505', '201504', '201503', '201502', '201501', '201412', '201411', '201410', '201409', '201408', '201407', '201406', '201405', '201404', '201403', '201402', '201401', '201312', '201311', '201310', '201309', '201308', '201307', '201306', '201305', '201304', '201303', '201302', '201301', '201212', '201211', '201210', '201209', '201208', '201207', '201206', '201205', '201204', '201203', '201202', '201201', '201112', '201111', '201110', '201109', '201108', '201107', '201106', '201105', '201104', '201103', '201102', '201101', '201012', '201011', '201010', '201009', '201008', '201007', '201006', '201005', '201004', '201003', '201002', '201001', '200912', '200911', '200910', '200909', '200908', '200907', '200906', '200905', '200904', '200903', '200902', '200901', '200812', '200811', '200810', '200809', '200808', '200807', '200806', '200805', '200804', '200803', '200802', '200801', '200712', '200711', '200710', '200709', '200708', '200707', '200706', '200705', '200704', '200703', '200702', '200701', '200612', '200611', '200610', '200609', '200608', '200607', '200606', '200605', '200604', '200603', '200602', '200601', '200512', '200511', '200510', '200509', '200508', '200507', '200506', '200505', '200504', '200503', '200502', '200501', '200412', '200411', '200410', '200409', '200408', '200407', '200406', '200405', '200404', '200403', '200402', '200401', '200312', '200311', '200310', '200309', '200308', '200307', '200306', '200305', '200304', '200303', '200302', '200301', '200212', '200211', '200210', '200209', '200208', '200207', '200206', '200205', '200204', '200203', '200202', '200201', '202605', '202604', '202603', '202602', '202601', '202512', '202511', '202510', '202509', '202508', '202507', '202506', '202505', '202504', '202503', '202502', '202501', '202412', '202411', '202410', '202409', '202408', '202407', '202406', '202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306', '202305', '202304', '202303', '202302', '202301', '202212', '202211', '202210', '202209', '202208', '202207', '202206', '202205', '202204', '202203', '202202', '202201', '202112', '202111', '202110', '202109', '202108', '202107', '202106', '202105', '202104', '202103', '202102', '202101', '202012', '202011', '202010', '202009', '202008', '202007', '202006', '202005', '202004', '202003', '202002', '202001', '201912', '201911', '201910', '201909', '201908', '201907', '201906', '201905', '201904', '201903', '201902', '201901', '201812', '201811', '201810', '201809', '201808', '201807', '201806', '201805', '201804', '201803', '201802', '201801', '201712', '201711', '201710', '201709', '201708', '201707', '201706', '201705', '201704', '201703', '201702', '201701', '201612', '201611', '201610', '201609', '201608', '201607', '201606', '201605', '201604', '201603', '201602', '201601', '201512', '201511', '201510', '201509', '201508', '201507', '201506', '201505', '201504', '201503', '201502', '201501', '201412', '201411', '201410', '201409', '201408', '201407', '201406', '201405', '201404', '201403', '201402', '201401', '201312', '201311', '201310', '201309', '201308', '201307', '201306', '201305', '201304', '201303', '201302', '201301', '201212', '201211', '201210', '201209', '201208', '201207', '201206', '201205', '201204', '201203', '201202', '201201', '201112', '201111', '201110', '201109', '201108', '201107', '201106', '201105', '201104', '201103', '201102', '201101', '201012', '201011', '201010', '201009', '201008', '201007', '201006', '201005', '201004', '201003', '201002', '201001', '200912', '200911', '200910', '200909', '200908', '200907', '200906', '200905', '200904', '200903', '200902', '200901', '200812', '200811', '200810', '200809', '200808', '200807', '200806', '200805', '200804', '200803', '200802', '200801', '200712', '200711', '200710', '200709', '200708', '200707', '200706', '200705', '200704', '200703', '200702', '200701', '200612', '200611', '200610', '200609', '200608', '200607', '200606', '200605', '200604', '200603', '200602', '200601', '200512', '200511', '200510', '200509', '200508', '200507', '200506', '200505', '200504', '200503', '200502', '200501', '200412', '200411', '200410', '200409', '200408', '200407', '200406', '200405', '200404', '200403', '200402', '200401', '200312', '200311', '200310', '200309', '200308', '200307', '200306', '200305', '200304', '200303', '200302', '200301', '200212', '200211', '200210', '200209', '200208', '200207', '200206', '200205', '200204', '200203', '200202', '200201', '202605', '202604', '202603', '202602', '202601', '202512', '202511', '202510', '202509', '202508', '202507', '202506', '202505', '202504', '202503', '202502', '202501', '202412', '202411', '202410', '202409', '202408', '202407', '202406', '202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306', '202305', '202304', '202303', '202302', '202301', '202212', '202211', '202210', '202209', '202208', '202207', '202206', '202205', '202204', '202203', '202202', '202201', '202112', '202111', '202110', '202109', '202108', '202107', '202106', '202105', '202104', '202103', '202102', '202101', '202012', '202011', '202010', '202009', '202008', '202007', '202006', '202005', '202004', '202003', '202002', '202001', '201912', '201911', '201910', '201909', '201908', '201907', '201906', '201905', '201904', '201903', '201902', '201901', '201812', '201811', '201810', '201809', '201808', '201807', '201806', '201805', '201804', '201803', '201802', '201801', '201712', '201711', '201710', '201709', '201708', '201707', '201706', '201705', '201704', '201703', '201702', '201701', '201612', '201611', '201610', '201609', '201608', '201607', '201606', '201605', '201604', '201603', '201602', '201601', '201512', '201511', '201510', '201509', '201508', '201507', '201506', '201505', '201504', '201503', '201502', '201501', '201412', '201411', '201410', '201409', '201408', '201407', '201406', '201405', '201404', '201403', '201402', '201401', '201312', '201311', '201310', '201309', '201308', '201307', '201306', '201305', '201304', '201303', '201302', '201301', '201212', '201211', '201210', '201209', '201208', '201207', '201206', '201205', '201204', '201203', '201202', '201201', '201112', '201111', '201110', '201109', '201108', '201107', '201106', '201105', '201104', '201103', '201102', '201101', '201012', '201011', '201010', '201009', '201008', '201007', '201006', '201005', '201004', '201003', '201002', '201001', '200912', '200911', '200910', '200909', '200908', '200907', '200906', '200905', '200904', '200903', '200902', '200901', '200812', '200811', '200810', '200809', '200808', '200807', '200806', '200805', '200804', '200803', '200802', '200801', '200712', '200711', '200710', '200709', '200708', '200707', '200706', '200705', '200704', '200703', '200702', '200701', '200612', '200611', '200610', '200609', '200608', '200607', '200606', '200605', '200604', '200603', '200602', '200601', '200512', '200511', '200510', '200509', '200508', '200507', '200506', '200505', '200504', '200503', '200502', '200501', '200412', '200411', '200410', '200409', '200408', '200407', '200406', '200405', '200404', '200403', '200402', '200401', '200312', '200311', '200310', '200309', '200308', '200307', '200306', '200305', '200304', '200303', '200302', '200301', '200212', '200211', '200210', '200209', '200208', '200207', '200206', '200205', '200204', '200203', '200202', '200201', '202605', '202604', '202603', '202602', '202601', '202512', '202511', '202510', '202509', '202508', '202507', '202506', '202505', '202504', '202503', '202502', '202501', '202412', '202411', '202410', '202409', '202408', '202407', '202406', '202405', '202404', '202403', '202402', '202401', '202312', '202311', '202310', '202309', '202308', '202307', '202306', '202305', '202304', '202303', '202302', '202301', '202212', '202211', '202210', '202209', '202208', '202207', '202206', '202205', '202204', '202203', '202202', '202201', '202112', '202111', '202110', '202109', '202108', '202107', '202106', '202105', '202104', '202103', '202102', '202101', '202012', '202011', '202010', '202009', '202008', '202007', '202006', '202005', '202004', '202003', '202002', '202001', '201912', '201911', '201910', '201909', '201908', '201907', '201906', '201905', '201904', '201903', '201902', '201901', '201812', '201811', '201810', '201809', '201808', '201807', '201806', '201805', '201804', '201803', '201802', '201801', '201712', '201711', '201710', '201709', '201708', '201707', '201706', '201705', '201704', '201703', '201702', '201701', '201612', '201611', '201610', '201609', '201608', '201607', '201606', '201605', '201604', '201603', '201602', '201601', '201512', '201511', '201510', '201509', '201508', '201507', '201506', '201505', '201504', '201503', '201502', '201501', '201412', '201411', '201410', '201409', '201408', '201407', '201406', '201405', '201404', '201403', '201402', '201401', '201312', '201311', '201310', '201309', '201308', '201307', '201306', '201305', '201304', '201303', '201302', '201301', '201212', '201211', '201210', '201209', '201208', '201207', '201206', '201205', '201204', '201203', '201202', '201201', '201112', '201111', '201110', '201109', '201108', '201107', '201106', '201105', '201104', '201103', '201102', '201101', '201012', '201011', '201010', '201009', '201008', '201007', '201006', '201005', '201004', '201003', '201002', '201001', '200912', '200911', '200910', '200909', '200908', '200907', '200906', '200905', '200904', '200903', '200902', '200901', '200812', '200811', '200810', '200809', '200808', '200807', '200806', '200805', '200804', '200803', '200802', '200801', '200712', '200711', '200710', '200709', '200708', '200707', '200706', '200705', '200704', '200703', '200702', '200701', '200612', '200611', '200610', '200609', '200608', '2006

In [33]:
ipc = pd.DataFrame(ipc)

ipc.sample(5)

       id_tiempo  id_territorio  id_sector  id_medida  valor_ipc
138298    202605              9          7          1    101.694
83445     200702              6          2          1     62.437
91944     200612              6          9          2     -1.800
174486    201312             11          9          4     -6.900
327772    201001             20         14          3      2.800

In [34]:
ipc.to_csv('../files/data_raw/ipc.csv', index=False)