In [1]:
# Importación de librerías
import pandas as pd
import numpy as np

# Configuración para visualizar todas las columnas
pd.set_option('display.max_columns', None)

1. Revisamos los archivos exportados para comprobar la integridad de los datos

In [2]:
df_empr_const = pd.read_csv('../files/data_raw/empresas_constituidas.csv')

In [3]:
df_empr_const.sample(5)

,id_const,territorio,id_tiempo,tipo,numero_sociedades,capital
8944,8945,"Asturias, Principado de",201404,Sociedades de responsabilidad limitada,117,2841000
6526,6527,Extremadura,201402,Sociedades anónimas,0,0
1631,1632,Castilla - La Mancha,201809,Mercantiles,169,4701000
5767,5768,Castilla - La Mancha,202205,Sociedades anónimas,0,0
3419,3420,País Vasco,201605,Mercantiles,259,28176000

In [4]:
df_empr_const.info()

<class 'pandas.DataFrame'>
RangeIndex: 16720 entries, 0 to 16719
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_const           16720 non-null  int64
 1   territorio         16720 non-null  str
 2   id_tiempo          16720 non-null  int64
 3   tipo               16720 non-null  str
 4   numero_sociedades  16720 non-null  int64
 5   capital            16720 non-null  int64
dtypes: int64(4), str(2)
memory usage: 783.9 KB

In [5]:
df_empr_const.describe(include='number').T

,count,mean,std,min,25%,50%,75%,max
id_const,16720.0,8.360500e+03,4.826793e+03,1.0,4180.75,8360.5,12540.25,1.672000e+04
id_tiempo,16720.0,2.016737e+05,5.294115e+02,200801.0,201207.75,201702.5,202109.25,2.026040e+05
numero_sociedades,16720.0,2.134034e+02,4.471220e+02,0.0,0.00,7.0,215.00,3.173000e+03
capital,16720.0,1.544442e+07,1.489657e+08,0.0,0.00,442000.0,7895000.00,1.259172e+10

In [6]:
df_empr_const.describe(include='string').T

            count unique          top  freq
territorio  16720     19    Andalucía   880
tipo        16720      4  Mercantiles  4180

In [7]:
df_empr_const["territorio"].unique()

<StringArray>
[                  'Andalucía',                      'Aragón',
     'Asturias, Principado de',              'Balears, Illes',
                    'Canarias',                   'Cantabria',
             'Castilla y León',        'Castilla - La Mancha',
                    'Cataluña',        'Comunitat Valenciana',
                 'Extremadura',                     'Galicia',
        'Madrid, Comunidad de',           'Murcia, Región de',
 'Navarra, Comunidad Foral de',                  'País Vasco',
                   'Rioja, La',                       'Ceuta',
                     'Melilla']
Length: 19, dtype: str

Pendiente de arreglar los nombres, minúsculas, tildes, etc. normalizar la columna

In [8]:
df_empr_const["tipo"].unique()

<StringArray>
[                           'Mercantiles',
                    'Sociedades anónimas',
 'Sociedades de responsabilidad limitada',
       'S. Comanditarias y S. Colectivas']
Length: 4, dtype: str

Tras revisar los tipos de empresa, nos damos cuenta que "Mercantiles" es un total de las empresas SL, y SA, vamos a comprobarlo.

In [9]:
df_empr_const[df_empr_const["tipo"] == "Mercantiles"].sample(10)

,id_const,territorio,id_tiempo,tipo,numero_sociedades,capital
713,714,"Balears, Illes",202111,Mercantiles,299,9549000
1257,1258,Cantabria,201303,Mercantiles,80,9328000
638,639,"Asturias, Principado de",200910,Mercantiles,76,2320000
1392,1393,Castilla y León,202004,Mercantiles,90,1335000
3135,3136,"Navarra, Comunidad Foral de",202109,Mercantiles,54,3345000
1806,1807,Cataluña,202206,Mercantiles,1589,52294000
3260,3261,"Navarra, Comunidad Foral de",201104,Mercantiles,66,1531000
382,383,Aragón,201210,Mercantiles,161,6472000
3833,3834,Ceuta,201807,Mercantiles,5,15000
2741,2742,"Madrid, Comunidad de",201711,Mercantiles,1774,62062000

In [10]:
df_empr_const["tipo"].value_counts()

tipo
Mercantiles                               4180
Sociedades anónimas                       4180
Sociedades de responsabilidad limitada    4180
S. Comanditarias y S. Colectivas          4180
Name: count, dtype: int64

La razón que los valores totales coinciden es porque hay una fila por fecha, independientemente si hay disueltas o no (0)

In [11]:
df_empr_const[df_empr_const["tipo"] == "Mercantiles"].shape

(4180, 6)

In [12]:
df_empr_const[(df_empr_const["territorio"] == "Melilla") & (df_empr_const["id_tiempo"] == 202505)].head(100)

,id_const,territorio,id_tiempo,tipo,numero_sociedades,capital
3971,3972,Melilla,202505,Mercantiles,10,1037000
8151,8152,Melilla,202505,Sociedades anónimas,0,0
12331,12332,Melilla,202505,Sociedades de responsabilidad limitada,10,1037000
16511,16512,Melilla,202505,S. Comanditarias y S. Colectivas,0,0

In [13]:
df_empr_const[(df_empr_const["territorio"] == "Canarias") & (df_empr_const["id_tiempo"] == 202006)].head(100)

,id_const,territorio,id_tiempo,tipo,numero_sociedades,capital
950,951,Canarias,202006,Mercantiles,186,155088000
5130,5131,Canarias,202006,Sociedades anónimas,0,0
9310,9311,Canarias,202006,Sociedades de responsabilidad limitada,186,155088000
13490,13491,Canarias,202006,S. Comanditarias y S. Colectivas,0,0

In [14]:
df_empr_const[(df_empr_const["territorio"] == "Andalucía") & (df_empr_const["id_tiempo"] == 202407)].head(100)

,id_const,territorio,id_tiempo,tipo,numero_sociedades,capital
21,22,Andalucía,202407,Mercantiles,1564,78298000
4201,4202,Andalucía,202407,Sociedades anónimas,2,1840000
8381,8382,Andalucía,202407,Sociedades de responsabilidad limitada,1562,76458000
12561,12562,Andalucía,202407,S. Comanditarias y S. Colectivas,0,0

Confirmamos nuestras sospechas, procederemos en el paso de transformación a eliminar esas filas. df_empr_const["tipo"] == "Mercantiles"

------------------------------------

In [15]:
df_empr_dis = pd.read_csv('../files/data_raw/empresas_disueltas.csv')

In [16]:
df_empr_dis.sample(5)

      id_dis         territorio  id_tiempo       razon  numero_sociedades
6441    6442        Extremadura     202103  Por fusión                  2
2931    2932  Murcia, Región de     202005  Voluntaria                  1
704      705     Balears, Illes     202208  Voluntaria                 58
204      205          Andalucía     200904  Voluntaria                159
4307    4308          Andalucía     201509  Por fusión                 25

In [17]:
df_empr_dis.info()

<class 'pandas.DataFrame'>
RangeIndex: 12540 entries, 0 to 12539
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_dis             12540 non-null  int64
 1   territorio         12540 non-null  str
 2   id_tiempo          12540 non-null  int64
 3   razon              12540 non-null  str
 4   numero_sociedades  12540 non-null  int64
dtypes: int64(3), str(2)
memory usage: 490.0 KB

In [18]:
df_empr_dis.shape

(12540, 5)

In [19]:
df_empr_dis.describe(include='number').T

,count,mean,std,min,25%,50%,75%,max
id_dis,12540.0,6270.500000,3620.130523,1.0,3135.75,6270.5,9405.25,12540.0
id_tiempo,12540.0,201673.700000,529.416812,200801.0,201207.75,201702.5,202109.25,202604.0
numero_sociedades,12540.0,32.513238,71.914047,0.0,2.00,8.0,31.00,1114.0

In [20]:
df_empr_dis.describe(include='string').T

            count unique         top  freq
territorio  12540     19   Andalucía   660
razon       12540      3  Voluntaria  4180

In [21]:
df_empr_dis["razon"].value_counts()

razon
Voluntaria    4180
Por fusión    4180
Otras         4180
Name: count, dtype: int64

La razón que los valores totales coinciden es porque hay una fila por fecha, independientemente si hay disueltas o no (0)

-------------------------

In [22]:
df_ipc = pd.read_csv('../files/data_raw/ipc.csv')

In [23]:
df_ipc.sample(10)

        id_tiempo  id_territorio  id_sector  id_medida  valor_ipc
113615     200709              8         13          4      2.300
88163      200406              7          6          1     78.316
254233     200907             17          7          4     -0.900
134757     200311             10          3          4      2.500
153772     200605             11          6          1     81.703
10145      201102              2          9          3     -2.000
165114     201306             12          1          4      0.200
13301      201609              2         12          2     -0.200
85124      201307              7          3          3      6.200
93683      200805              7         10          4      0.900

In [24]:
df_ipc.info()

<class 'pandas.DataFrame'>
RangeIndex: 311752 entries, 0 to 311751
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id_tiempo      311752 non-null  int64
 1   id_territorio  311752 non-null  int64
 2   id_sector      311752 non-null  int64
 3   id_medida      311752 non-null  int64
 4   valor_ipc      311752 non-null  float64
dtypes: float64(1), int64(4)
memory usage: 11.9 MB

In [25]:
df_ipc.describe(include='number').T

,count,mean,std,min,25%,50%,75%,max
id_tiempo,311752.0,201377.771331,705.028615,200201.0,200802.00,201403.0,202004.00000,202605.000
id_territorio,311752.0,11.000000,5.477234,2.0,6.00,11.0,16.00000,20.000
id_sector,311752.0,7.500000,4.031135,1.0,4.00,7.5,11.00000,14.000
id_medida,311752.0,2.500000,1.118036,1.0,1.75,2.5,3.25000,4.000
valor_ipc,311752.0,21.504041,37.066418,-22.4,0.10,1.5,37.37975,258.216

In [26]:
df_ipc[df_ipc["valor_ipc"] == -22.4].head()

        id_tiempo  id_territorio  id_sector  id_medida  valor_ipc
169387     202308             12          5          3      -22.4

In [27]:
df_ipc[df_ipc["valor_ipc"] <0].sample(10)

        id_tiempo  id_territorio  id_sector  id_medida  valor_ipc
279921     201707             19          1          4       -1.0
38213      201602              4          5          3       -7.1
204691     201108             14          7          3       -2.0
155183     201011             11          7          2       -0.3
184300     202602             13          4          2       -1.4
272931     201401             18          9          4       -1.8
267933     201506             18          5          3       -1.0
286729     201110             19          7          3       -0.8
41726      201605              4          8          3       -4.5
55939      200312              5          6          3       -0.2

----------------

In [28]:
df_sectores_ipc = pd.read_csv('../files/data_raw/sectores_ipc.csv')

In [29]:
df_sectores_ipc.sample(10)

    id_sector                                      nombre_sector
12         13                    Seguros y servicios financieros
2           3                       Bebidas alcohólicas y tabaco
1           2                 Alimentos y bebidas no alcohólicas
8           9                       Información y comunicaciones
5           6  Muebles, artículos del hogar y artículos para ...
0           1                                     Índice general
9          10         Actividades recreativas, deporte y cultura
6           7                                            Sanidad
10         11                                          Enseñanza
13         14  Cuidado personal, protección social, y bienes ...

In [30]:
df_sectores_ipc.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_sector      14 non-null     int64
 1   nombre_sector  14 non-null     str
dtypes: int64(1), str(1)
memory usage: 356.0 bytes

In [31]:
df_sectores_ipc.describe(include='number').T

           count  mean     std  min   25%  50%    75%   max
id_sector   14.0   7.5  4.1833  1.0  4.25  7.5  10.75  14.0

In [32]:
df_sectores_ipc.describe(include='string').T

              count unique             top freq
nombre_sector    14     14  Índice general    1

In [33]:
df_sectores_ipc["nombre_sector"].unique()

<StringArray>
[                                                                    'Índice general',
                                                 'Alimentos y bebidas no alcohólicas',
                                                       'Bebidas alcohólicas y tabaco',
                                                                  'Vestido y calzado',
                             'Vivienda, agua, electricidad, gas y otros combustibles',
 'Muebles, artículos del hogar y artículos para el mantenimiento corriente del hogar',
                                                                            'Sanidad',
                                                                         'Transporte',
                                                       'Información y comunicaciones',
                                         'Actividades recreativas, deporte y cultura',
                                                                          'Enseñanza',
                                            'Restaurantes y servicios de alojamiento',
                                                    'Seguros y servicios financieros',
                 'Cuidado personal, protección social, y bienes y servicios diversos']
Length: 14, dtype: str

------------------

In [34]:
df_territorio = pd.read_csv('../files/data_raw/territorio.csv')

In [35]:
df_territorio.sample(10)

    id_territorio            nombre_territorio
15             16  Navarra, Comunidad Foral de
13             14         Madrid, Comunidad de
8               9         Castilla - La Mancha
0               1                     Nacional
2               3                       Aragón
6               7                    Cantabria
11             12                  Extremadura
12             13                      Galicia
10             11         Comunitat Valenciana
17             18                    Rioja, La

In [36]:
df_territorio.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_territorio      20 non-null     int64
 1   nombre_territorio  20 non-null     str
dtypes: int64(1), str(1)
memory usage: 452.0 bytes

In [37]:
df_territorio.describe(include='string').T

                  count unique       top freq
nombre_territorio    20     20  Nacional    1

In [38]:
df_territorio["nombre_territorio"].unique()

<StringArray>
[                   'Nacional',                   'Andalucía',
                      'Aragón',     'Asturias, Principado de',
              'Balears, Illes',                    'Canarias',
                   'Cantabria',             'Castilla y León',
        'Castilla - La Mancha',                    'Cataluña',
        'Comunitat Valenciana',                 'Extremadura',
                     'Galicia',        'Madrid, Comunidad de',
           'Murcia, Región de', 'Navarra, Comunidad Foral de',
                  'País Vasco',                   'Rioja, La',
                       'Ceuta',                     'Melilla']
Length: 20, dtype: str

-----------------

In [39]:
df_tiempo = pd.read_csv('../files/data_raw/tiempo.csv')

In [40]:
df_tiempo.sample(10)

     id_tiempo  anio  mes  nombre_mes
240     200605  2006    5        Mayo
129     201508  2015    8      Agosto
127     201510  2015   10     Octubre
75      202002  2020    2     Febrero
171     201202  2012    2     Febrero
261     200408  2004    8      Agosto
64      202101  2021    1       Enero
0       202605  2026    5        Mayo
90      201811  2018   11   Noviembre
272     200309  2003    9  Septiembre

In [41]:
df_tiempo.info()

<class 'pandas.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_tiempo   294 non-null    int64
 1   anio        294 non-null    int64
 2   mes         294 non-null    int64
 3   nombre_mes  294 non-null    str
dtypes: int64(3), str(1)
memory usage: 9.3 KB

In [42]:
df_tiempo.describe(include='number').T

,count,mean,std,min,25%,50%,75%,max
id_tiempo,294.0,201381.948980,708.657083,200201.0,200802.25,201403.5,202004.75,202606.0
anio,294.0,2013.755102,7.087548,2002.0,2008.00,2014.0,2020.00,2026.0
mes,294.0,6.438776,3.457394,1.0,3.00,6.0,9.00,12.0

---------------------

In [43]:
df_tipo_medida = pd.read_csv('../files/data_raw/tipo_medida.csv')

In [44]:
df_tipo_medida.head(10)

   id_medida                  nombre_medida
0          1                         Índice
1          2              Variación mensual
2          3                Variación anual
3          4  Variación en lo que va de año

In [45]:
df_tipo_medida.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_medida      4 non-null      int64
 1   nombre_medida  4 non-null      str
dtypes: int64(1), str(1)
memory usage: 196.0 bytes

In [46]:
df_tipo_medida.value_counts()

id_medida  nombre_medida
1          Índice                           1
2          Variación mensual                1
3          Variación anual                  1
4          Variación en lo que va de año    1
Name: count, dtype: int64