In [28]:
# Configuración del sistema para encontrar la carpeta raíz
import sys
import os

import pandas as pd
# Esto obliga a Python a mirar una carpeta hacia atrás (donde está 'src')
sys.path.append(os.path.abspath(os.path.join('..')))
sys.path.append(os.path.abspath(os.path.join('.')))

# Importación del módulo de transformacion
from src.transformacion import trans_str
from src.transformacion import trans_normal
# Configuración para visualizar todas las columnas
pd.set_option('display.max_columns', None)

Abrimos los ficheros

In [29]:
df_empr_const = pd.read_csv('../files/data_raw/empresas_constituidas.csv')
df_empr_dis = pd.read_csv('../files/data_raw/empresas_disueltas.csv')
df_ipc = pd.read_csv('../files/data_raw/ipc.csv')
df_sectores_ipc = pd.read_csv('../files/data_raw/sectores_ipc.csv')
df_territorio = pd.read_csv('../files/data_raw/territorio.csv')
df_tiempo = pd.read_csv('../files/data_raw/tiempo.csv')
df_tipo_medida = pd.read_csv('../files/data_raw/tipo_medida.csv')

Transformamos id's, año y mes a string ya que son falsas numericas (actuan como categoricas)

In [30]:
# Listas de columnas a transformar de cada DataFrame
lista_const = ['id_const', 'id_tiempo']
lista_dis = ['id_dis', 'id_tiempo']
lista_ipc = ['id_tiempo', 'id_territorio', 'id_sector', 'id_medida']
lista_sector_ipc = ['id_sector']
lista_territorio = ['id_territorio']
lista_tiempo = ['id_tiempo', 'anio', 'mes']
lista_tipo_medida = ['id_medida']

In [31]:
trans_str.int_a_str(df_empr_const, lista_const)
trans_str.int_a_str(df_empr_dis, lista_dis)
trans_str.int_a_str(df_ipc, lista_ipc)
trans_str.int_a_str(df_sectores_ipc, lista_sector_ipc)
trans_str.int_a_str(df_territorio, lista_territorio)
trans_str.int_a_str(df_tiempo, lista_tiempo)
trans_str.int_a_str(df_tipo_medida, lista_tipo_medida)

-> Columna 'id_const' convertida a str.
-> Columna 'id_tiempo' convertida a str.
-> Columna 'id_dis' convertida a str.
-> Columna 'id_tiempo' convertida a str.
-> Columna 'id_tiempo' convertida a str.
-> Columna 'id_territorio' convertida a str.
-> Columna 'id_sector' convertida a str.
-> Columna 'id_medida' convertida a str.
-> Columna 'id_sector' convertida a str.
-> Columna 'id_territorio' convertida a str.
-> Columna 'id_tiempo' convertida a str.
-> Columna 'anio' convertida a str.
-> Columna 'mes' convertida a str.
-> Columna 'id_medida' convertida a str.

  id_medida                  nombre_medida
0         1                         Índice
1         2              Variación mensual
2         3                Variación anual
3         4  Variación en lo que va de año

In [32]:
df_empr_const.info()

<class 'pandas.DataFrame'>
RangeIndex: 16720 entries, 0 to 16719
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_const           16720 non-null  str
 1   territorio         16720 non-null  str
 2   id_tiempo          16720 non-null  str
 3   tipo               16720 non-null  str
 4   numero_sociedades  16720 non-null  int64
 5   capital            16720 non-null  int64
dtypes: int64(2), str(4)
memory usage: 783.9 KB

In [33]:
df_empr_dis.info()

<class 'pandas.DataFrame'>
RangeIndex: 12540 entries, 0 to 12539
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_dis             12540 non-null  str
 1   territorio         12540 non-null  str
 2   id_tiempo          12540 non-null  str
 3   razon              12540 non-null  str
 4   numero_sociedades  12540 non-null  int64
dtypes: int64(1), str(4)
memory usage: 490.0 KB

In [34]:
df_ipc.info()

<class 'pandas.DataFrame'>
RangeIndex: 311752 entries, 0 to 311751
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id_tiempo      311752 non-null  str
 1   id_territorio  311752 non-null  str
 2   id_sector      311752 non-null  str
 3   id_medida      311752 non-null  str
 4   valor_ipc      311752 non-null  float64
dtypes: float64(1), str(4)
memory usage: 11.9 MB

In [35]:
df_sectores_ipc.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_sector      14 non-null     str
 1   nombre_sector  14 non-null     str
dtypes: str(2)
memory usage: 356.0 bytes

In [36]:
df_territorio.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_territorio      20 non-null     str
 1   nombre_territorio  20 non-null     str
dtypes: str(2)
memory usage: 452.0 bytes

In [37]:
df_tiempo.info()

<class 'pandas.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_tiempo   294 non-null    str
 1   anio        294 non-null    str
 2   mes         294 non-null    str
 3   nombre_mes  294 non-null    str
dtypes: str(4)
memory usage: 9.3 KB

In [38]:
df_tipo_medida.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_medida      4 non-null      str
 1   nombre_medida  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

Cambiar los Nombres de las comunidades autonomas, sin acentos, con minusculas y separacion con guion bajo ('_')
DataFrames: empresas_constituidas, empresas_disueltas y territorio

In [ ]:
# Creamos el diccionario de mapeo con tus especificaciones exactas
mapeo_territorios = {
    "Nacional": "nacional",
    "Andalucía": "andalucia",
    "Aragón": "aragon",
    "Asturias, Principado de": "principado_de_asturias",
    "Balears, Illes": "illes_balears",
    "Canarias": "canarias",
    "Cantabria": "cantabria",
    "Castilla y León": "castilla_y_leon",
    "Castilla - La Mancha": "castilla_la_mancha",
    "Cataluña": "cataluna",
    "Comunitat Valenciana": "comunitat_valenciana",
    "Extremadura": "extremadura",
    "Galicia": "galicia",
    "Madrid, Comunidad de": "comunidad_de_madrid",
    "Murcia, Región de": "region_de_murcia",
    "Navarra, Comunidad Foral de": "comunidad_foral_de_navarra",
    "País Vasco": "pais_vasco",
    "Rioja, La": "la_rioja",
    "Ceuta": "ceuta",
    "Melilla": "melilla"
}

In [40]:
df_empr_const['territorio'] = df_empr_const['territorio'].replace(mapeo_territorios)
df_empr_dis['territorio'] = df_empr_dis['territorio'].replace(mapeo_territorios)
df_territorio['nombre_territorio'] = df_territorio['nombre_territorio'].replace(mapeo_territorios)

In [41]:
df_empr_const['territorio'].unique()

<StringArray>
[                 'andalucia',                     'aragon',
     'principado_de_asturias',              'illes_balears',
                   'canarias',                  'cantabria',
            'castilla_y_leon',         'castilla_la_mancha',
                   'cataluna',       'comunitat_valenciana',
                'extremadura',                    'galicia',
        'comunidad_de_madrid',           'region_de_murcia',
 'comunidad_foral_de_navarra',                 'pais_vasco',
                   'la_rioja',                      'ceuta',
                    'melilla']
Length: 19, dtype: str

In [42]:
df_empr_dis['territorio'].unique()

<StringArray>
[                 'andalucia',                     'aragon',
     'principado_de_asturias',              'illes_balears',
                   'canarias',                  'cantabria',
            'castilla_y_leon',         'castilla_la_mancha',
                   'cataluna',       'comunitat_valenciana',
                'extremadura',                    'galicia',
        'comunidad_de_madrid',           'region_de_murcia',
 'comunidad_foral_de_navarra',                 'pais_vasco',
                   'la_rioja',                      'ceuta',
                    'melilla']
Length: 19, dtype: str

In [43]:
df_territorio['nombre_territorio'].unique()

<StringArray>
[                  'nacional',                  'andalucia',
                     'aragon',     'principado_de_asturias',
              'illes_balears',                   'canarias',
                  'cantabria',            'castilla_y_leon',
         'castilla_la_mancha',                   'cataluna',
       'comunitat_valenciana',                'extremadura',
                    'galicia',        'comunidad_de_madrid',
           'region_de_murcia', 'comunidad_foral_de_navarra',
                 'pais_vasco',                   'la_rioja',
                      'ceuta',                    'melilla']
Length: 20, dtype: str

Normalizamos resto de columnas (minisculas, separacion con guion bajo ('_'))

In [44]:
# Así se aplica una función a los DATOS de una columna
df_empr_dis["razon"] = df_empr_dis["razon"].apply(trans_normal.normalizar_col)
df_sectores_ipc["nombre_sector"] = df_sectores_ipc["nombre_sector"].apply(trans_normal.normalizar_col)
df_tiempo["nombre_mes"] = df_tiempo["nombre_mes"].apply(trans_normal.normalizar_col)
df_tipo_medida["nombre_medida"] = df_tipo_medida["nombre_medida"].apply(trans_normal.normalizar_col)

In [45]:
df_empr_dis.sample(10)

,id_dis,territorio,id_tiempo,razon,numero_sociedades
4747,4748,principado_de_asturias,201509,por_fusion,1
4219,4220,andalucia,202301,por_fusion,24
2598,2599,galicia,201106,voluntaria,68
8586,8587,aragon,202510,otras,4
7332,7333,comunidad_foral_de_navarra,202004,por_fusion,2
376,377,aragon,201304,voluntaria,51
9867,9868,castilla_y_leon,201009,otras,6
7077,7078,region_de_murcia,202303,por_fusion,5
2274,2275,extremadura,202002,voluntaria,28
8043,8044,ceuta,201601,por_fusion,0

In [48]:
df_sectores_ipc.sample(10)

   id_sector                                      nombre_sector
0          1                                     indice_general
8          9                       informacion_y_comunicaciones
6          7                                            sanidad
11        12            restaurantes_y_servicios_de_alojamiento
10        11                                          ensenanza
12        13                    seguros_y_servicios_financieros
13        14  cuidado_personal_proteccion_social_y_bienes_y_...
7          8                                         transporte
2          3                       bebidas_alcoholicas_y_tabaco
4          5  vivienda_agua_electricidad_gas_y_otros_combust...

In [49]:
df_tiempo.sample(10)

    id_tiempo  anio mes  nombre_mes
40     202301  2023   1       enero
269    200312  2003  12   diciembre
169    201204  2012   4       abril
209    200812  2008  12   diciembre
293    202606  2026   6       junio
282    200211  2002  11   noviembre
164    201209  2012   9  septiembre
41     202212  2022  12   diciembre
288    200205  2002   5        mayo
279    200302  2003   2     febrero

In [52]:
df_tipo_medida.sample(4)

  id_medida                  nombre_medida
3         4  variacion_en_lo_que_va_de_ano
0         1                         indice
2         3                variacion_anual
1         2              variacion_mensual

Eliminar en empresas_contituidas las tipo mercantiles, son sumatorias del resto de tipo y nos duplican los datos

In [ ]:
# Eliminamos las filas que contienen "Mercantiles"
df_empr_const = df_empr_const[df_empr_const['tipo'] != 'Mercantiles']

In [56]:
df_empr_const['tipo'].unique()

<StringArray>
[                   'Sociedades anónimas',
 'Sociedades de responsabilidad limitada',
       'S. Comanditarias y S. Colectivas']
Length: 3, dtype: str

In [57]:
df_empr_const.shape

(12540, 6)

Cambiamos el nombre de las sociedades por sus acronimos

In [58]:
# Creamos el diccionario de mapeo con tus especificaciones exactas
dicc_siglas = {
    'Sociedades de responsabilidad limitada': 'S.L.',
    'Sociedades anónimas': 'S.A.',
    'S. Comanditarias y S. Colectivas': 'S.Com./S.C.'
}

In [59]:
# Aplicamos el cambio a la columna 'tipo'
df_empr_const['tipo'] = df_empr_const['tipo'].replace(dicc_siglas)

In [60]:
df_empr_const['tipo'].unique()

<StringArray>
['S.A.', 'S.L.', 'S.Com./S.C.']
Length: 3, dtype: str

Guardamos los csv's procesados

In [62]:
df_empr_const.to_csv('../files/data_processed/empresas_constituidas.csv', index=False)
df_empr_dis.to_csv('../files/data_processed/empresas_disueltas.csv', index=False)
df_ipc.to_csv('../files/data_processed/ipc.csv', index=False)
df_sectores_ipc.to_csv('../files/data_processed/sectores_ipc.csv', index=False)
df_territorio.to_csv('../files/data_processed/territorio.csv', index=False)
df_tiempo.to_csv('../files/data_processed/tiempo.csv', index=False)
df_tipo_medida.to_csv('../files/data_processed/tipo_medida.csv', index=False)